services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "hexagonal-rails"
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3100 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    ports:
      - "3100:3100"
    depends_on:
      - db
